-- models/marts/dims/dim_date.sql
SELECT
    ORDER_DATE AS DATE,
    TO_CHAR(ORDER_DATE, 'YYYY-MM-DD') AS DATE_KEY,
    EXTRACT(year FROM ORDER_DATE) AS YEAR,
    EXTRACT(month FROM ORDER_DATE) AS MONTH,
    TO_CHAR(ORDER_DATE, 'Month') AS MONTH_NAME,
    EXTRACT(day FROM ORDER_DATE) AS DAY,
    TO_CHAR(ORDER_DATE, 'Day') AS DAY_NAME,
    CASE WHEN EXTRACT(dow FROM ORDER_DATE) IN (0,6) THEN 'Weekend' ELSE 'Weekday' END AS DAY_TYPE
FROM (
    SELECT DISTINCT ORDER_DATE FROM {{ ref('stg_orders') }}
)
